/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TshirtsRouteImport } from './routes/tshirts'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as LegCastRouteImport } from './routes/leg-cast'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ArmSlingRouteImport } from './routes/arm-sling'
import { Route as ArmCastRouteImport } from './routes/arm-cast'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TshirtsRoute = TshirtsRouteImport.update({
  id: '/tshirts',
  path: '/tshirts',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const LegCastRoute = LegCastRouteImport.update({
  id: '/leg-cast',
  path: '/leg-cast',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmSlingRoute = ArmSlingRouteImport.update({
  id: '/arm-sling',
  path: '/arm-sling',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmCastRoute = ArmCastRouteImport.update({
  id: '/arm-cast',
  path: '/arm-cast',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arm-cast': typeof ArmCastRoute
  '/arm-sling': typeof ArmSlingRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/leg-cast': typeof LegCastRoute
  '/testimonials': typeof TestimonialsRoute
  '/tshirts': typeof TshirtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arm-cast': typeof ArmCastRoute
  '/arm-sling': typeof ArmSlingRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/leg-cast': typeof LegCastRoute
  '/testimonials': typeof TestimonialsRoute
  '/tshirts': typeof TshirtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arm-cast': typeof ArmCastRoute
  '/arm-sling': typeof ArmSlingRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/leg-cast': typeof LegCastRoute
  '/testimonials': typeof TestimonialsRoute
  '/tshirts': typeof TshirtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/arm-cast'
    | '/arm-sling'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/leg-cast'
    | '/testimonials'
    | '/tshirts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arm-cast'
    | '/arm-sling'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/leg-cast'
    | '/testimonials'
    | '/tshirts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/arm-cast'
    | '/arm-sling'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/leg-cast'
    | '/testimonials'
    | '/tshirts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArmCastRoute: typeof ArmCastRoute
  ArmSlingRoute: typeof ArmSlingRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LegCastRoute: typeof LegCastRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TshirtsRoute: typeof TshirtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tshirts': {
      id: '/tshirts'
      path: '/tshirts'
      fullPath: '/tshirts'
      preLoaderRoute: typeof TshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leg-cast': {
      id: '/leg-cast'
      path: '/leg-cast'
      fullPath: '/leg-cast'
      preLoaderRoute: typeof LegCastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arm-sling': {
      id: '/arm-sling'
      path: '/arm-sling'
      fullPath: '/arm-sling'
      preLoaderRoute: typeof ArmSlingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arm-cast': {
      id: '/arm-cast'
      path: '/arm-cast'
      fullPath: '/arm-cast'
      preLoaderRoute: typeof ArmCastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArmCastRoute: ArmCastRoute,
  ArmSlingRoute: ArmSlingRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LegCastRoute: LegCastRoute,
  TestimonialsRoute: TestimonialsRoute,
  TshirtsRoute: TshirtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
